version: "3.9"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./faiss_store:/app/faiss_store
      - type: bind
        source: ./chatbot.db
        target: /app/chatbot.db
        bind:
          create_host_path: true
      - type: bind
        source: ./auth.db
        target: /app/auth.db
        bind:
          create_host_path: true
      - type: bind
        source: ./thread_names.json
        target: /app/thread_names.json
        bind:
          create_host_path: true
    restart: unless-stopped